### ISSUE TITLE
Project checklist

### ISSUE THREAD

**Issue by codeandclay** [codeandclay/goodi.sh#4]
This checklist is for keeping track of what's been done a what needs to be done. I intend to add and remove items as necessary.

#### Project
- [x] A project has one owner.
~~- [ ] A project has many contributors.~~
    ~~- Contributors have roles.~~
- [x] It has many comments.
- [x] It has many reactions.

- [x] A project has a non-sequential id.
- [x] It has a name.
    - [x] It can't be blank.
    - [x] It can be changed.
- [x] Has many dependent external links:
    - A project url.
    - An optional github url.
- [x] It has a description.
    - [x] It cannot be blank.
    - [x] It can be changed.
- [x] It has many images.
    - [x] Images are validate

#### Contributor
~~A person credited with contributing to a project.~~
~~- [ ] Can point to a user.~~
~~- [ ] Has external links.~~
~~- [ ] Has role.~~

#### User
- [x] A user has many projects.
- [x] It has many comments.

- [x] A user has a non-sequential id.
- [x] A user has a name.
- [x] A user must have a profile.

#### Profile
This model represents who the user is IRL.
- [x] It has a name.
- [x] It has a biography.
- [x] A user has a profile picture.
    - [x] The image is validated.
- [x] A user has optional external links.

#### Comment
- [x] A comment belongs to a project.
- [x] A comment has an author.
- [x] A comment is dependent on the author.
- [x] A comment is dependent on the project.
- [x] A comment has many reactions.

#### Reactions
See issue: #1
- [x] A reaction has many projects.
- [x] A reaction has many comments.

#### External links
Can be associated with multiple models.
- [x] Has a valid url.
- [x] Has a single `link_owner`.
- [x] Has a label.

**Comment by codeandclay** [comment]
Closing as I'm using Trello.
